name: mosdnsui

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: alpine-latest

    steps:
    - uses: actions/checkout@v4
    - name: mosdnsui
      run: docker build . --file Dockerfile --tag mosdnsui:$(date +%s)
