name: mosdnsui

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: mosdnsui
      run: docker build . --file Dockerfile --tag mosdnsui:$(date +%s)

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.MOSDNS_TOKEN }}
      run: |
        gh release create v0.0.1
